package com.hayate0726.tides.ui.export

import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.hayate0726.tides.domain.CycleStats
import com.hayate0726.tides.domain.model.Cycle
import com.hayate0726.tides.domain.model.Symptom
import java.io.OutputStream
import java.time.format.DateTimeFormatter

/**
 * Builds the "Cycle Summary" PDF — report-card style for personal use.
 * Pure Android PdfDocument; no third-party libs.
 *
 * Page: US Letter (612 × 792 pt). Black ink on white only — readable when
 * printed or photocopied. 12pt body, 18pt headers.
 */
object PdfBuilder {

    private const val PAGE_WIDTH = 612
    private const val PAGE_HEIGHT = 792
    private const val MARGIN = 48
    private const val LINE_HEIGHT = 18

    fun buildCycleSummary(
        cycles: List<Cycle>,
        stats: CycleStats,
        symptomTopN: List<Pair<Symptom, Int>>,
        appVersion: String,
        output: OutputStream,
    ) {
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
        val page = doc.startPage(pageInfo)
        val canvas = page.canvas

        val title = Paint().apply {
            color = Color.BLACK; textSize = 22f; isAntiAlias = true
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
        }
        val label = Paint().apply { color = Color.DKGRAY; textSize = 10f; isAntiAlias = true }
        val body = Paint().apply { color = Color.BLACK; textSize = 12f; isAntiAlias = true }
        val small = Paint().apply { color = Color.DKGRAY; textSize = 9f; isAntiAlias = true }

        var y = MARGIN + 24
        canvas.drawText("Cycle Summary", MARGIN.toFloat(), y.toFloat(), title)
        y += 28

        canvas.drawText("AVERAGES", MARGIN.toFloat(), y.toFloat(), label); y += LINE_HEIGHT
        canvas.drawText(
            "Median cycle length: ${stats.medianCycleLength ?: "—"} days",
            MARGIN.toFloat(), y.toFloat(), body,
        ); y += LINE_HEIGHT
        canvas.drawText(
            "Median period length: ${stats.medianPeriodLength ?: "—"} days",
            MARGIN.toFloat(), y.toFloat(), body,
        ); y += LINE_HEIGHT
        canvas.drawText(
            "Cycles tracked: ${stats.completedCycleCount}",
            MARGIN.toFloat(), y.toFloat(), body,
        ); y += LINE_HEIGHT * 2

        canvas.drawText("CYCLES", MARGIN.toFloat(), y.toFloat(), label); y += LINE_HEIGHT
        val fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd")
        for (c in cycles) {
            val text = "${c.start.format(fmt)}  length=${c.length ?: "—"}d  period=${c.periodLength ?: "—"}d"
            canvas.drawText(text, MARGIN.toFloat(), y.toFloat(), body)
            y += LINE_HEIGHT
            if (y > PAGE_HEIGHT - MARGIN) break  // Plan 4 v1: one page; pagination is a future task
        }

        y = PAGE_HEIGHT - MARGIN
        canvas.drawText(
            "Generated by Tides v$appVersion. Not a medical document. Do not use for diagnosis.",
            MARGIN.toFloat(), y.toFloat(), small,
        )

        doc.finishPage(page)
        doc.writeTo(output)
        doc.close()
    }
}
